# Site settings
title: à la code
header-img: img/home-bg.png
email: mtanhder@icloud.com
copyright_name: mckayanhder
description: > # this means to ignore newlines until "baseurl:"
  A means to a 'begining'
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mckayanhder
learn_profile: mckayanhder
email_username: mtanhder@icloud.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
